# Generated by Django 2.2 on 2019-04-11 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('summary', models.CharField(max_length=400)),
                ('topic', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
