# Generated by Django 2.2 on 2019-04-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='summary',
            field=models.CharField(max_length=1200),
        ),
    ]
