# Generated by Django 2.2 on 2019-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
