# Generated by Django 2.2 on 2019-05-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190507_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='summary',
            field=models.CharField(max_length=5000),
        ),
    ]
