# Generated by Django 2.2 on 2019-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_due', models.DateTimeField()),
                ('difficulty', models.CharField(choices=[('EA', 'Easy'), ('MD', 'Brave'), ('HD', 'Jedi')], default='MD', max_length=2)),
            ],
        ),
    ]
